### ISSUE TITLE
Subfont does not detect content in ::marker pseudo-element

### ISSUE THREAD

**Issue by CxRes** [Munter/subfont#166]
I have a code that looks something like this:

```css
@font-face {
    font-family: Noto Color Emoji;
    src: ...
}

ul li::marker {
    font-family: Noto Color Emoji;
    content: "\2713";
}
```

Subfont does not seem to detect this for some reason. I can work around it by adding the character manually but it is not as nice as having it automatically detected.
