### ISSUE TITLE
Font family is undetected when applied via class selector which contains escaped colon

### ISSUE THREAD

**Issue by joeldbirch** [Munter/subfont#173]
Font family is undetected when applied via class selector which contains escaped colon.

For example, I am using a [utility CSS library named Hucssley](https://github.com/stowball/hucssley) which generates classes containing colons to separate property names from values.

```css
.font-family\:default {
    font-family: Some Custom Font, sans-serif;
}
```
```html
    <h1 class="font-family:default">font-family is applied but subfont doesn't detect it</h1>
```

When this selector is used to apply the font-family to an element, subfont does not detect the font-family as being used. However, if I manually change the CSS so a colon is not used, and I use that altered class in the HTML, subfont works as expected.

```css
.font-family-default {
    font-family: Some Custom Font, sans-serif;
}
```
```html
    <h1 class="font-family-default">font-family is applied and subfont DOES detects it</h1>
```
