### ISSUE TITLE
Support fonts set in CSS custom properties

### ISSUE THREAD

**Issue by seaneking** [Munter/subfont#23]
Using subfont on font declarations using [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) fails. 

Ie: subfont doesn't detect that any font families are being used here, so doesn't subset anything
```css
:root {
  --body-font: 'Lato', sans-serif;
}
body {
  font-family: var(--body-font);
}
```

Again looks like jsdom isn't going to support this any time soon (https://github.com/jsdom/jsdom/issues/1895), would headless chrome rather than jsdom be an option? Would give you a 1:1 environment for analysing this stuff. I know that's what Critical uses and it works a charm.

**Comment by papandreou** [comment]
Oh, yikes. Yeah, we don't support that yet. We don't depend on jsdom's CSS support at all, so it's on us.

@Munter, this one is going to be fun, especially for variables with different definitions in `@media { ... }` blocks etc.

It might be fairly easy to support to 90% case where variables only have one definition, though.

**Comment by papandreou** [comment]
@seaneking, thanks for bringing it to our attention ;)

**Comment by seaneking** [comment]
> It might be fairly easy to support to 90% case where variables only have one definition, though

I think that's a totally fair caveat - can't imagine many use cases where you'd be changing font families dynamically in media queries and such

**Comment by papandreou** [comment]
@seaneking, agreed. We already support that when variables aren't involved, though :)

```html
<style>
  h1 {
    font-family: foo;
  }

  @media 3dglasses {
    h1 {
      font-family: bar;
    }
  }
</style>
<h1>baz</h1>
```

In the above case, we will add `baz` to the subsets of both the `foo` and `bar` fonts.

**Comment by seaneking** [comment]
¯\\_(ツ)_/¯ 

Still, if it means quickfix vs. big deal, chucking a note in the README saying that that custom props are only parsed under X circumstances is a good first step. Certainly no worse than the current position haha.

**Comment by papandreou** [comment]
Certainly! PR for that note is welcome. Will look into supporting the 90% case within a few weeks.

**Comment by papandreou** [comment]
Ah, I misread what you meant that the note should say. Nvm about the PR :)

**Comment by seaneking** [comment]
Just realised another roadblock re: custom elements - would subfont work with components in general? Content passed as props, rendered in shadow dom, js templates, etc?

**Comment by papandreou** [comment]
[glyphhanger](https://www.npmjs.com/package/glyphhanger) is an example. There are pros and cons. It doesn’t support tracing `@media` blocks individually and including list indicators in the subsets (AFAIK).

**Comment by ignacionr** [comment]
So sorry to see that you guys don't care for CSS. The lack of flex-related CSS properties makes is an incredible bummer. As to the question of "not being able to imagine changing /whatever-css/ on the fly" please realize there are so many libraries that create interface elements from the ground up like this.

**Comment by papandreou** [comment]
@ignacionr, I’m not sure I understand what you mean? Why wouldn’t subfont support flexbox? An example would go a long way.

Also, please be respectful. We’ve spent many evenings building this tool, and let me assure you that we care very deeply about CSS ;)

**Comment by ignacionr** [comment]
Really sorry, in the frenzy of searching for an answer, I stumbled upon the link (first comment in thread https://github.com/jsdom/jsdom/issues/1895 ) and I was actually referring to that project and their team's lack of support etc. So the comment was directed at another team and ended up here because of my mistake. Sincere apologies.

Just in case the original poster cares, in order to solve my own issue I hunted for the correct jsdom dependency and made a PR for it at https://github.com/chad3814/CSSStyleDeclaration/pull/56 .

I do understand your feeling uncomfortable and clueless as to where this was coming from. Owe you.

**Comment by papandreou** [comment]
@seaneking, making good progress with this over at https://github.com/assetgraph/assetgraph/pull/874 -- do you happen to have a publicly accessible site that I can test the implementation against?

**Comment by seaneking** [comment]
Hrm not really sorry, could make a minimal repro in a few lines though? Just a matter of defining a font stack in vars then applying it on an element.

**Comment by papandreou** [comment]
@seaneking, oh okay. I have made a bunch of synthetic test cases myself, so that probably wouldn't help much. I think I need some bigger, "real world" things to try it on.

**Comment by seaneking** [comment]
Is there a fork I can pull down myself? Have an internal project using fonts in vars extensively that I can test it on and report back.

**Comment by seaneking** [comment]
Here you go: https://github.com/seaneking/littleplanet-test

It's not that 'big' a site (and still a WIP, ignore placeholder media haha), but uses a fair few font families exclusively via CSS custom props. That repo is the output of a [Gatsby](https://www.gatsbyjs.org/) build, so it's a hot mess in terms of code structure. 

But the important points for this issue:

- All fonts are defined in `font` stacks as CSS vars in `:root` (eg: `--font-body`, `--font-headings`, etc)
- _All_ font declarations are via those vars, no direct `font-family` or other decls are used
- Fonts files are consumed locally
- A good test case for subfont would be the `--font-display` stack with Abril Fatface, since only a handful of characters are used (on case studies, under `work/`)

Let me know if there's anything else you want me to clear up.

**Comment by papandreou** [comment]
Thanks a lot, I'll try to get that site to work :)

The actual change to trace custom properties is in assetgraph, but I've put up a branch in subfont that has a git dep on the relevant assetgraph branch, if you'd like to play with it:

```
npm install -g Munter/subfont#customProperties
```

**Comment by papandreou** [comment]
Seems like we're in a place now where all the characters on the littleplanet site are traced out correctly: https://gist.github.com/papandreou/b5021effdb56d914a131da00807080ff

However, we'll need a bit of creativity to inject the subset fonts into `font` and `font-family` property values when custom properties are in use:

```css
:root {
    --font-heading: 900 var(--scale-4)/1.3 "Montserrat", sans-serif;
    --font-subheading: 700 var(--scale-2)/1.3 "Lato", sans-serif;
    --font-body: 400 var(--scale-0)/1.5 "Lato", sans-serif;
    --font-article: 400 var(--scale-0)/1.5 "Lora", serif;
    --font-ui: 400 var(--scale-0)/1 "Lato", sans-serif;
    --font-ui-heavy: 900 var(--scale-0)/1 "Lato", sans-serif;
    --font-ui-heavy-letter-spacing: .03em;
    --font-display: 400 var(--scale-6)/1 "Abril Fatface", cursive;
}

@media (min-width:48em) {
    :root {
        --font-heading: 900 var(--scale-5)/1.3 "Montserrat", sans-serif;
        --font-subheading: 700 var(--scale-3)/1.3 "Lato", sans-serif;
    }
}

/* ... */

body {
    font: var(--font-body);
    position: relative;
    margin: 0;
}

h1 {
    font: var(--font-heading);
}

h2, h3, h4, h5, h6 {
    font: var(--font-subheading);
}

/* ... */

.src-components-Label----styles-module---label---3CjkR {
    display: block;
    font: var(--font-ui);
    color: var(--color-grey-500);
    margin: .6em 0;
}

/* ... */
```

@Munter, what dælen do we do? :)

**Comment by Munter** [comment]
That's a very good question. I don't have any good idea just looking at that CSS example right now. I'm afraid my head might start to hurt thinking about it :)

**Comment by papandreou** [comment]
Yeah, I'm hoping we won't have to backtrack into all the places where the involved custom vars are defined. That'll probably also be impossible in the general case, as multiple `var(--foo)` expansions can take place in one property, and it happens at the token level, so you could even have:

```css
body {
  --foo: 12px;
  --bar: MyFont;
  --quux: MyOtherFont;
  font: var(--foo) var(--bar), var(--quux);
}
```

I'm happy that the first example I posted (which was extracted from the littleplanet site that @seaneking provided) has examples of conditionally defined custom properties in a media query -- tracing that is working. I thought I was so close to the finish line :)

**Comment by papandreou** [comment]
Maybe it'd be OK to just patch any custom property that contains the name of the font that we've subset.

There's a small risk of accidentally patching custom properties with string literals that end up in `content` properties, but if we do some naive tracking of which custom properties (hypothetically) contributed to each `font` and `font-family` value, it might be fine.

**Comment by papandreou** [comment]
I've [implemented a "backtracking" solution](https://github.com/assetgraph/assetgraph/commit/6a513b38139e0d117816b4db80adef6b97d35104) that will patch up every custom property that is referenced (directly or indirectly) from a `font` or a `font-family` property AND contains the name of a font that has had a subset generated.

That means the first part of the above example from the littleplanet site will come out as:

```css
:root {
    --font-heading: 900 var(--scale-4)/1.3 'Montserrat__subset', "Montserrat", sans-serif;
    --font-subheading: 700 var(--scale-2)/1.3 'Lato__subset', "Lato", sans-serif;
    --font-body: 400 var(--scale-0)/1.5 'Lato__subset', "Lato", sans-serif;
    --font-article: 400 var(--scale-0)/1.5 'Lora__subset', "Lora", serif;
    --font-ui: 400 var(--scale-0)/1 'Lato__subset', "Lato", sans-serif;
    --font-ui-heavy: 900 var(--scale-0)/1 'Lato__subset', "Lato", sans-serif;
    --font-ui-heavy-letter-spacing: .03em;
    --font-display: 400 var(--scale-6)/1 'Abril Fatface__subset', "Abril Fatface", cursive;
}

@media (min-width:48em) {
    :root {
        --font-heading: 900 var(--scale-5)/1.3 'Montserrat__subset', "Montserrat", sans-serif;
        --font-subheading: 700 var(--scale-3)/1.3 'Lato__subset', "Lato", sans-serif;
    }
}
```

It was a bit of work, but it feels reasonably safe :)

**Comment by papandreou** [comment]
It obviously won't support something like:

```css
:root {
  --foo: Abril;
  --bar: Fatface;
  font: var(--foo) var(--bar);
}
```

... but I sincerely hope nobody does that :)

**Comment by seaneking** [comment]
Awesome! 

And pretty sure that second example is invalid CSS anyway - custom props aren't just regexed out by the browser, so (AFAIK) can't compose values like that

**Comment by papandreou** [comment]
@seaneking, you're partly right in that custom properties [are substituted at the token level](https://drafts.csswg.org/css-variables/#substitute-a-var), so you can't do arbitrary string concatenation. However, although [the spec](https://drafts.csswg.org/css-fonts-3/#font-family-prop) recommends that font names containing spaces are quoted as strings, it goes on to say:

> Font family names other than generic families must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means most punctuation characters and digits at the start of each token must be escaped in unquoted font family names.

So unfortunately this does work:

```html
<html>
<head>
    <style>
        @font-face {
            font-family: Abril Fatface;
            src: url(/static/abril-fatface-latin-400.76a43cc8.woff2) format("woff2");
        }
        :root {
            --foo: Abril;
            --bar: Fatface;
            font-family: var(--foo) var(--bar);
        }
    </style>
</head>
<body>
    <p>Hello, world!</p>
</body>
</html>
```

Theoretically we could loosen it up and patch every occurrence of the first identifer/word of the font family so the above would come out as:

```css
:root {
  --foo: 'Abril Fatface__subset', Abril;
  --bar: Fatface;
  font-family: var(--foo) var(--bar);
}
```

... but it feels like it's getting too weird and error prone. Let's wait with that until someone convinces us that it's necessary.
