### ISSUE TITLE
Upgrading from 3.5.0 to 3.6.0 causes changes I don't understand

### ISSUE THREAD

**Issue by dotlouis** [Munter/subfont#43]
Hello,
Back from a small holiday onto the great problem of font loading ⚡️ 
I've upgraded subfont from 3.5.0 to 3.6.0 and I'm seeing some odd changes in the generated inline CSS.

The only changes between the two URLs is the subfont version
**3.5.0** https://5b68725267610c2d6ced4cd0--webv5.netlify.com/
**3.6.0** https://5b685e6edd28ef61ae4726bd--webv5.netlify.com/

_I suggest you enable request blocking in the devtools and exclude `cdn.segment.com` not to load third party resources and analytics._

Now the weird part is that in the 3.5 version, font subsets are (pre)loaded correctly at high priority. Then the google font version takes over at lower priority because downloaded asynchronously via the JS.
<img width="1098" alt="screen shot 2018-08-06 at 18 23 09" src="https://user-images.githubusercontent.com/1891109/43728607-e6ff375e-99a5-11e8-9514-ac7f8ea62c00.png">

In the 3.6 version however, font subsets are still loaded correctly at high priority but now, the full variant (ttf) is not loaded from google fonts anymore but from the local files and at _highest priority_ (because it's now in a font-face declaration).
<img width="1257" alt="screen shot 2018-08-06 at 18 23 28" src="https://user-images.githubusercontent.com/1891109/43728734-46349fa2-99a6-11e8-9d1c-7d7d0d6e986a.png">

Besides, there is a weird css file that tries to be downloaded but (obviously) does not exist.

I guess the change in font priority is a good thing because it does not wait for JS evaluation to download the whole font. But I don't get what cause all these changes, in particular, why the `ttf` now comes from local files instead of google font which is less performant for delivering font files.

The inline css changes added in 3.6 are:

```CSS
            @font-face {
                font-family: Titillium Web__subset;
                font-stretch: normal;
                font-style: normal;
                font-weight: 300;
                src: local("Titillium Web Light"),local("TitilliumWeb-Light"),url(/subfont/Titillium_Web-300-7b715e7d41.ttf) format("truetype")
            }

            @font-face {
                font-family: Titillium Web__subset;
                font-stretch: normal;
                font-style: normal;
                font-weight: 400;
                src: local("Titillium Web Regular"),local("TitilliumWeb-Regular"),url(/subfont/Titillium_Web-400-9ea639a9cb.ttf) format("truetype")
            }

            @font-face {
                font-family: Titillium Web__subset;
                font-stretch: normal;
                font-style: normal;
                font-weight: 600;
                src: local("Titillium Web SemiBold"),local("TitilliumWeb-SemiBold"),url(/subfont/Titillium_Web-600-aca1fc3f50.ttf) format("truetype")
            }

            @font-face {
                font-family: Titillium Web__subset;
                font-stretch: normal;
                font-style: normal;
                font-weight: 700;
                src: local("Titillium Web Bold"),local("TitilliumWeb-Bold"),url(/subfont/Titillium_Web-700-1c962a5033.ttf) format("truetype")
            }

            @font-face {
                font-family: Titillium Web__subset;
                font-stretch: normal;
                font-style: normal;
                font-weight: 900;
                src: local("Titillium Web Black"),local("TitilliumWeb-Black"),url(/subfont/Titillium_Web-900-3b3c25dc87.ttf) format("truetype")
            }
```

Can you help me understand this ?
Thanks
