### ISSUE TITLE
How to include `font-display: swap` with subfont?

### ISSUE THREAD

**Issue by ajmalafif** [Munter/subfont#47]
I am using Subfont with Gatsby through https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-subfont

Thanks for the awesome work, I love how things just work with subfont! I am by all means not an expert in JS, i'm using subfont and Gatsby because it's great accessible tools for beginner like myself. 

I am stuck at how do I include `@font-face { font-display:swap;}` with subfont because I tried to do it myself, but it doesn't seem to pick it up:

Repo: https://github.com/ajmalafif/gatsby-interUI/blob/master/src/components/layout.js
Example: https://gatsby-interui.netlify.com/

![2cnazc4q](https://user-images.githubusercontent.com/827167/50099913-2dc97380-025a-11e9-9f87-7badaa2f7b22.png)

### font-display though included in the code, not picked up by the browser
![veqaks4g](https://user-images.githubusercontent.com/827167/50101823-8ef34600-025e-11e9-8f85-0981a19fb3e2.png)

**Comment by papandreou** [comment]
Hmm, when I clone your repo and run `gatsby build`, `font-display: swap` does get injected into the `@font-face` declaration for the subset font:

```css
      @font-face {
        font-display: swap;
        font-family: Inter UI__subset;
        font-stretch: normal;
        font-style: normal;
        font-weight: 600;
        src: url(/subfont/Inter_UI-600-7e943e72da.woff2) format('woff2'),
          url(/subfont/Inter_UI-600-c99b110d8d.woff) format('woff');
        unicode-range: U+65, U+69, U+6c, U+6e-70, U+72-74, U+76, U+79, U+20,
          U+32, U+47-49, U+55, U+61-62;
      }
```

That does not seem to be the case on https://gatsby-interui.netlify.com -- in fact it looks like (gatsby-plugin-)subfont didn't run during the build at all! Did you turn off subfont again and rebuild after reporting this issue?

Also, could you explain exactly what you expected to happen?
