### ISSUE TITLE
Flash after fallback starts loading

### ISSUE THREAD

**Issue by PierreAndreis** [Munter/subfont#69]
I'm noticing that after the fallback font starts loading, I'm getting a flash of unstyled content.
Is it possible to get the browser to keep the first font loaded and just swap after the fallback is done loaded? Otherwise, the flash seems worse than if it was just initial.

Network was running with slow 3g simulator and disabled cache
![Kapture 2019-11-10 at 23 08 57](https://user-images.githubusercontent.com/5843816/68567954-1ca7c900-040f-11ea-9889-854ff7375422.gif)

You can check the website live at https://useloud.netlify.com
I can upload the source code if needed. Running gatsby with gatsby-plugin-subfont on.

Thoughts?

**Comment by Munter** [comment]
Your styles.tsx:35 contains a global font style application that sets the font to `Bison` instead of the subfont generated `Bison__subset`.

styles.tsx:35:
```css
      html {
        font-family: 'Bison', Arial, sans-serif;
        font-weight: 500;
        color: white;
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%;
      }
```

Subfonts  modified CSS declaration in the HTML:

```css
html{font-family:Bison__subset, 'Bison', Arial, sans-serif;font-weight:500;color:white;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;}
```

Your rehydration is undoing the work subfont did by switching in the fallback font as the primary one, which then gives you the well-known flash of invisible text before the fallbacks load.

Subfont doesn't know about emotion generated styles and thus can't modify them. Since you are statically rendering on build, does it even make sense to have emotion rehydrate the global CSS?
