### ISSUE TITLE
Fonts Loaded Twice

### ISSUE THREAD

**Issue by s0kil** [Munter/subfont#96]
I'm using subfont with the `--in-place --recursive --inline-css --no-fallbacks` options and subfont loads:
`/subfont/Merriweather-400-e495e5bac2.woff2`
and `https://d33wubrfki0l68.cloudfront.net/195ab6bc68a36c0e71bb9bca8925cb2de363e038/04814/subfont/merriweather-400-e495e5bac2.woff2`
in order.

Is this the intended behavior? My conclusion is that both files are identical since the file size is the same.

**Comment by papandreou** [comment]
Hey @s0kil, that doesn't sound like the intended behavior, especially not with `--no-fallbacks`. Are you able to share some more details about the web page that you're using subfont on? Ideally a copy of the assets in their state before you run that command.

**Comment by s0kil** [comment]
Here is the page live: https://europeanmarketus.com/
These are the fonts used:
```html
    <!-- Fonts -->
    <style>
      /* Cera Pro Black Bold */
      @font-face {
        font-family: "cera_pro_black";
        font-style: normal;
        font-weight: 700;
        font-display: swap;
        src: url("/fonts/cerapro/cerapro-black-webfont.woff2") format("woff2"),
          url("/fonts/cerapro/cerapro-black-webfont.woff") format("woff");
      }
      /* Merriweather Regular */
      @font-face {
        font-family: "Merriweather";
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local("Merriweather Regular"), local("Merriweather-Regular"),
          url("/fonts/merriweather/merriweather-regular.woff2") format("woff2"),
          url("/fonts/merriweather/merriweather-regular.woff") format("woff");
      }
      /* Lato Regular */
      @font-face {
        font-family: "Lato";
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local("Lato Regular"), local("Lato-Regular"),
          url("/fonts/lato/lato-regular.woff2") format("woff2"),
          url("/fonts/lato/lato-regular.woff") format("woff");
      }
    </style>
```

**Comment by papandreou** [comment]
@s0kil, it would really help if you could share the web page without subfont applied?

**Comment by papandreou** [comment]
It could look like there's a bad interaction between subfont and some other build steps you're running?

At a glance, it looks like https://europeanmarketus.com/subfont/Merriweather-400-e495e5bac2.woff2 gets loaded because of the `<link rel=preload>`:

```html
      <link rel="preload" as="font" type="font/woff2" crossorigin="anonymous" href="https://europeanmarketus.com/subfont/Merriweather-400-e495e5bac2.woff2">
```

And then https://d33wubrfki0l68.cloudfront.net/195ab6bc68a36c0e71bb9bca8925cb2de363e038/04814/subfont/merriweather-400-e495e5bac2.woff2 gets loaded because it's listed as the `src` of the subset font:

```css
@font-face {
  font-display: swap;
  font-family: Merriweather__subset;
  font-stretch: normal;
  font-style: normal;
  font-weight: 400;
  src: url("https://d33wubrfki0l68.cloudfront.net/195ab6bc68a36c0e71bb9bca8925cb2de363e038/04814/subfont/merriweather-400-e495e5bac2.woff2") format("woff2"), url("https://d33wubrfki0l68.cloudfront.net/2a57b8c66b13d4aa4af68772447df1d14ebb3547/8dc08/subfont/merriweather-400-a59ab8f1cc.woff") format("woff");
  unicode-range:U+64-69,U+6b-70,U+72-79,U+20,U+26,U+2b-2c,U+32,U+35,U+39,U+41-49,U+4c-50,U+53-54,U+57,U+61-63
}
```

My best bet is that you have you have step that moves assets to the CloudFront CDN and rewrites the references after subfont has run, but that tool does not rewrite the `<link rel=preload ...>` tags.

If that's the case, could you try running subfont as the last step instead?
